# Identificación del proyecto
sonar.projectKey=verificacion_firma_digital_mf
sonar.projectName=verificacion_firma_digital_mf
sonar.projectVersion=1.0
#sonar.host.url=https://sonarqube.portaloas.udistrital.edu.co/

# Directorios del código fuente
sonar.sources=src

# Archivos a excluir (build, node_modules, etc.)
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss

# Archivos de prueba
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Lenguaje y codificación
sonar.language=ts
sonar.sourceEncoding=UTF-8